"""Export M2 run evidence from the Modal volume into the repo and regenerate docs/STATUS.md's M2 section.

Everything STATUS.md claims about M2 is computed from files this script copies into
docs/evidence/m2/, so a reader can check each claim without re-running anything:

  python modal_worker/m2_report.py --mode debug --mode scaled

Cost comes from `modal billing report` (actual metered cost per Modal app run), not from an
estimate. Modal publishes billing in completed hourly buckets, so right after a run it can be
missing; the report then says "pending" and you re-run this script later.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

import modal

sys.path.insert(0, str(Path(__file__).resolve().parent))
from satq_m2 import metrics as M  # noqa: E402

REPO = Path(__file__).resolve().parents[1]
EVIDENCE = REPO / "docs" / "evidence" / "m2"
STATUS = REPO / "docs" / "STATUS.md"
VOLUME_NAME = "satquery-m1-vol"
MODEL_DIR = "/models/geochat-7b-llava-hf"
BEGIN, END = "<!-- M2:BEGIN (generated by modal_worker/m2_report.py) -->", "<!-- M2:END -->"
A10G_RATE = 1.10

RUN_FILES = [
    "runs.jsonl", "events.jsonl", "loss_history.json", "train_summary.json", "final_manifest.json",
    "results.json", "data/split_stats.json", "eval/base_metrics.json", "eval/adapted_metrics.json",
    "eval/base_predictions.jsonl", "eval/adapted_predictions.jsonl",
]


def ckpt_dir(mode: str) -> str:
    return f"/checkpoints/m2_geochat/{mode}"


def fetch(vol, remote: str, local: Path) -> bool:
    try:
        data = b"".join(vol.read_file(remote))
    except Exception:
        return False
    local.parent.mkdir(parents=True, exist_ok=True)
    local.write_bytes(data)
    return True


def listing(vol, remote: str) -> list[dict]:
    try:
        entries = vol.listdir(remote, recursive=True)
    except Exception:
        return []
    return [{"path": e.path, "bytes": e.size} for e in entries if e.type.name == "FILE"]


def load(path: Path):
    if not path.exists():
        return None
    if path.suffix == ".jsonl":
        return [json.loads(line) for line in path.read_text().splitlines() if line.strip()]
    return json.loads(path.read_text())


def billing(app_ids: set[str], start: datetime, last_activity: datetime) -> dict:
    """Actual cost for these Modal app runs from `modal billing report` (one row per app/hour/resource).

    Modal only publishes completed hourly buckets, so the result is 'partial' until the bucket that
    contains the run's last recorded activity has been published.
    """
    cmd = [sys.executable, "-m", "modal", "billing", "report", "--start", start.strftime("%Y-%m-%d"),
           "-r", "h", "--json", "--show-resources"]
    raw = re.sub(r"\x1b\[[0-9;]*m", "", subprocess.run(cmd, capture_output=True, text=True).stdout)
    try:
        rows = json.loads(raw)
    except json.JSONDecodeError:
        return {"status": "unavailable", "detail": raw[:300]}
    published_until = max(
        (datetime.fromisoformat(r["interval_start"]).replace(tzinfo=timezone.utc) + timedelta(hours=1) for r in rows),
        default=None,
    )
    by_resource: dict[str, float] = {}
    for r in rows:
        if r.get("object_id") in app_ids:
            by_resource[r["resource"]] = by_resource.get(r["resource"], 0.0) + float(r["cost"])
    gpu = sum(v for k, v in by_resource.items() if re.search(r"gpu|nvidia|a10|a100|h100|l4", k, re.I))
    complete = published_until is not None and published_until >= last_activity
    return {
        "status": "actual" if complete and by_resource else "partial",
        "detail": None if complete else f"billing published up to {published_until}; run active until {last_activity}",
        "source": "modal billing report --json --show-resources -r h",
        "app_ids": sorted(app_ids),
        "by_resource_usd": {k: round(v, 4) for k, v in sorted(by_resource.items())},
        "total_usd": round(sum(by_resource.values()), 4),
        "gpu_usd": round(gpu, 4),
        "gpu_hours_A10G": round(gpu / A10G_RATE, 3),
    }


def loss_svg(history: list[dict], title: str) -> str:
    w, h, pad = 640, 260, 40
    xs = [e["step"] for e in history]
    ys = [e["loss"] for e in history]
    x0, x1 = min(xs), max(xs) if max(xs) > min(xs) else min(xs) + 1
    y0, y1 = min(ys), max(ys) if max(ys) > min(ys) else min(ys) + 1
    pts = " ".join(
        f"{pad + (x - x0) / (x1 - x0) * (w - 2 * pad):.1f},{h - pad - (y - y0) / (y1 - y0) * (h - 2 * pad):.1f}"
        for x, y in zip(xs, ys)
    )
    return f"""<svg xmlns="http://www.w3.org/2000/svg" width="{w}" height="{h}" viewBox="0 0 {w} {h}" font-family="sans-serif" font-size="12">
<rect width="{w}" height="{h}" fill="white"/>
<text x="{pad}" y="20">{title}</text>
<line x1="{pad}" y1="{h - pad}" x2="{w - pad}" y2="{h - pad}" stroke="#888"/>
<line x1="{pad}" y1="{pad}" x2="{pad}" y2="{h - pad}" stroke="#888"/>
<text x="{pad}" y="{h - 12}">step {x0}</text><text x="{w - pad - 60}" y="{h - 12}">step {x1}</text>
<text x="4" y="{pad + 4}">{y1:.2f}</text><text x="4" y="{h - pad}">{y0:.2f}</text>
<polyline fill="none" stroke="#2563eb" stroke-width="1.5" points="{pts}"/>
</svg>
"""


def export(mode: str, vol) -> dict:
    out = EVIDENCE / mode
    got = {f: fetch(vol, f"{ckpt_dir(mode)}/{f}", out / f) for f in RUN_FILES}
    files = listing(vol, ckpt_dir(mode))
    (out / "volume_listing.json").write_text(json.dumps(files, indent=2))
    history = load(out / "loss_history.json") or []
    if history:
        (out / "loss_curve.svg").write_text(loss_svg(history, f"M2 {mode}: training loss per optimizer step"))
    runs = load(out / "runs.jsonl") or []
    events = load(out / "events.jsonl") or []
    start = min((datetime.fromisoformat(r["ts"]) for r in runs), default=datetime.now(timezone.utc)) - timedelta(days=1)
    last = max((datetime.fromisoformat(e["ts"]) for e in events), default=datetime.now(timezone.utc))
    # `--until verify` runs only convert/verify GeoChat, a one-off shared cost reported on its own
    run_apps = {r["app_id"] for r in runs if r.get("app_id", "unknown") != "unknown" and r.get("until") != "verify"}
    conv_apps = {r["app_id"] for r in runs if r.get("app_id", "unknown") != "unknown" and r.get("until") == "verify"}
    cost = billing(run_apps, start, last) if run_apps else {"status": "pending", "detail": "no app ids recorded"}
    (out / "cost.json").write_text(json.dumps(cost, indent=2))
    if conv_apps:
        conv_last = max(datetime.fromisoformat(r["ts"]) for r in runs if r.get("until") == "verify") + timedelta(hours=1)
        conv_path = EVIDENCE / "geochat_conversion" / "cost.json"
        conv_path.parent.mkdir(parents=True, exist_ok=True)
        conv_path.write_text(json.dumps(billing(conv_apps, start, conv_last), indent=2))
    return {"fetched": got, "files": files, "cost": cost}


def _rescore(records: list[dict]) -> list[dict]:
    for r in records:
        r["score"] = M.score_record(r["type"], r["prediction"], r["reference_output"])
    return records


def before_after(mode: str) -> list[dict] | None:
    """Rebuild the before/after table from the per-example predictions with the current scoring code."""
    d = EVIDENCE / mode / "eval"
    base, adapted = load(d / "base_predictions.jsonl"), load(d / "adapted_predictions.jsonl")
    if not base or not adapted:
        return None
    adapted = _rescore(adapted)
    rows = M.before_after_table(
        M.aggregate(_rescore(base)), M.aggregate(adapted), trivial=M.trivial_baselines(adapted)
    )
    (EVIDENCE / mode / "before_after.json").write_text(json.dumps(rows, indent=2))
    (EVIDENCE / mode / "before_after.md").write_text(M.table_markdown(rows) + "\n")
    return rows


def fmt_dist(d: dict) -> str:
    return ", ".join(f"{k}: {v}" for k, v in d.items())


def section(modes: list[str]) -> str:
    conv = load(EVIDENCE / "geochat_conversion" / "conversion.json")
    ver = load(EVIDENCE / "geochat_conversion" / "verification.json")
    L = [BEGIN, "", "## Team LoRA Checkpoint (M2 — BigEarthNet.txt on GeoChat-7B)", ""]

    L += ["### Base model", ""]
    if ver:
        c = ver["checks"]
        L += [
            f"**Base model used:** `MBZUAI/geochat-7B` @ `{conv['source']['revision'][:7]}` (Apache-2.0) — no substitution.",
            "",
            "GeoChat is published in the original LLaVA training layout (`GeoChatLlamaForCausalLM`, `model_type: geochat`), "
            "so `LlavaForConditionalGeneration.from_pretrained` fails with *\"The checkpoint you are trying to load has model type "
            "`geochat` but Transformers does not recognize this architecture\"*. `convert_geochat` rewrites it once into the "
            "llava-hf layout, rebuilding GeoChat's vision tower exactly as its loader does (CLIP ViT-L/14-336, position "
            "embeddings bicubic-interpolated to 504 px → 1,296 image tokens).",
            "",
            f"**Conversion check vs. the original GeoChat code** ({ver['reference']}), on {len(c)} prompts — "
            f"**{'PASSED' if ver['passed'] else 'FAILED'}** ([verification.json](evidence/m2/geochat_conversion/verification.json)):",
            "",
            "| Prompt | identical input ids | pixel max abs diff | next-token argmax identical | logits cosine | greedy text identical |",
            "|---|---|---|---|---|---|",
        ]
        for x in c:
            q = x["question"].split("\n")[0][:48]
            L.append(
                f"| `{q}` | {x['input_ids_identical']} | {x['pixel_max_abs_diff']:.1e} | "
                f"{x['argmax_identical']} | {x['logits_cosine']:.5f} | {x['generation_identical']} |"
            )
        L.append("")
        conv_cost = load(EVIDENCE / "geochat_conversion" / "cost.json")
        if conv_cost:
            L += [f"One-off conversion + verification cost (all attempts, incl. 3 that stopped early on strict "
                  f"weight checks): ${conv_cost['total_usd']:.2f} ({conv_cost['status']}).", ""]
    else:
        L += ["Conversion/verification evidence not exported yet.", ""]

    L += [
        "### Architecture decision",
        "",
        "A **fresh** `LoraConfig` (r=32, α=64, dropout 0.05) on GeoChat's language-model attention and MLP projections "
        "(`q/k/v/o_proj`, `gate/up/down_proj`), vision tower and projector frozen. We did **not** continue the M1 EuroSAT "
        "adapter: it was trained on generic LLaVA-1.5 weights, so it does not apply to GeoChat's weights, and GeoChat is "
        "already remote-sensing adapted by its authors. QLoRA: 4-bit NF4 base with double quantization, bf16 compute "
        "and bf16 training (not fp16).",
        "",
        "Prompts follow GeoChat's own conventions (`llava_v1` template; `[refer] … <p>phrase</p>` for grounding; boxes as "
        "`{<x1><y1><x2><y2>|<90>}` on a 0–100 grid, converted from BigEarthNet.txt's `[x1 y1, x2 y2]`, whose x-first order "
        "was checked on 1,610 relative-position questions). The base model is evaluated with the same prompts, so the "
        "baseline measures GeoChat's real ability rather than its unfamiliarity with a new syntax. Images are Sentinel-2 "
        "B04/B03/B02 rendered with the same 2–98% per-band stretch the backend uses for previews "
        "(`backend/app/ingestion/preview.py`; a unit test fails if the two drift apart).",
        "",
    ]

    for mode in modes:
        d = EVIDENCE / mode
        stats, summ, res, cost = (load(d / f) for f in ("data/split_stats.json", "train_summary.json", "results.json", "cost.json"))
        events = load(d / "events.jsonl") or []
        manifest = load(d / "final_manifest.json")
        L += [f"### {mode.capitalize()} run", ""]
        if stats:
            L += [
                f"**Dataset:** `{stats['annotations']}`; imagery `{stats['imagery']}`; filter {stats['filters']}. "
                f"Train rows from the official `train` split, eval rows from the official `test` split "
                f"(patch overlap: {stats['train_eval_patch_overlap']}).",
                "",
                f"- Train subset: **{stats['train']['n']}** rows over {stats['train']['unique_patches']} patches — "
                f"{fmt_dist(stats['train']['by_type'])}",
                f"- Held-out eval subset: **{stats['eval']['n']}** rows over {stats['eval']['unique_patches']} patches — "
                f"{fmt_dist(stats['eval']['by_type'])}",
                f"- Type/category distribution (train): {fmt_dist(stats['train']['by_type_category'])}",
                "",
            ]
        if summ:
            resumes = [e for e in events if e["event"] == "resumed"]
            L += [
                f"**Training:** {summ['train_rows']} rows × {summ['epochs']} epoch, effective batch {summ['effective_batch']}, "
                f"{summ['global_steps']} optimizer steps, {summ['trainable_params']:,} trainable params. "
                f"Mean loss first 20% of steps **{summ['loss_first_20pct_mean']:.3f}** → last 20% **{summ['loss_last_20pct_mean']:.3f}** "
                f"(NaN: {summ['loss_any_nan']}). Loss history: [loss_history.json](evidence/m2/{mode}/loss_history.json), "
                f"[loss_curve.svg](evidence/m2/{mode}/loss_curve.svg).",
                "",
            ]
            if resumes:
                r = resumes[-1]
                pre = next((e for e in events if e["event"] == "preempted"), None)
                how = (f"Modal preempted the GPU container after step {pre['last_logged_step_before_preemption']} "
                       f"(\"{pre['message'].split('.')[0]}\") and restarted the function automatically; it"
                       if pre else "the run was stopped manually (`modal app stop`) and relaunched; it")
                L += [f"**Resume after interruption:** tested — {how} resumed from `{Path(r['from_checkpoint']).name}` "
                      f"at global step {r['global_step']} with the loss history intact "
                      f"([events.jsonl](evidence/m2/{mode}/events.jsonl)).", ""]
            for e in (e for e in events if e["event"] == "discarded"):
                L += [f"**Discarded attempt:** {', '.join(e['what'])} — {e['reason']}", ""]
        if manifest:
            a = manifest["files"]["adapter_model.safetensors"]
            L += [f"**Checkpoint:** `{manifest['path']}/adapter_model.safetensors` — {a['bytes']:,} bytes, sha256 `{a['sha256'][:16]}…` "
                  f"(on the Modal volume `{VOLUME_NAME}`; [final_manifest.json](evidence/m2/{mode}/final_manifest.json)).", ""]
        if cost:
            if cost["status"] in ("actual", "partial") and cost.get("by_resource_usd"):
                label = "actual" if cost["status"] == "actual" else "PARTIAL — later hours not yet published by Modal"
                L += [f"**GPU time & cost ({label}, `modal billing report`):** {cost['gpu_hours_A10G']} A10G-hours; "
                      f"${cost['total_usd']:.2f} total (GPU ${cost['gpu_usd']:.2f}; "
                      f"{', '.join(f'{k} ${v:.2f}' for k, v in cost['by_resource_usd'].items())}) across app runs "
                      f"{', '.join(cost['app_ids'])}.", ""]
            if cost["status"] != "actual":
                L += [f"**GPU time & cost:** not final — {cost.get('detail', '')}. Re-run `python modal_worker/m2_report.py` later.", ""]
        rows = before_after(mode)
        if rows:
            L += ["**Before/after on the held-out split** — both models 4-bit, greedy decoding, identical prompts "
                  f"([before_after.json](evidence/m2/{mode}/before_after.json); per-example predictions in "
                  f"[eval/](evidence/m2/{mode}/eval/)):", "", M.table_markdown(rows), ""]
            L += [
                "How to read it: MCQ categories *country*, *season* and *climate zone* have (near-)constant answers in "
                "this Lithuania/Summer subset, so the *image-dependent* MCQ row is the honest VQA number. Reference "
                "captions share a fixed opening (\"This satellite image, captured during the summer in Lithuania…\"), "
                "which inflates ROUGE-L/BLEU once that template is learned; LULC-class F1 is the content check. "
                "The ±column is not shown per row, but at n=100 a proportion has a 95% half-width of about ±0.10.",
                "",
            ]
            not_learned = [r for r in rows if r.get("trivial_baseline") is not None and r["adapted"] < r["trivial_baseline"] + 0.05]
            if not_learned:
                L += ["**Not learned** — post-adaptation score is within 0.05 of an image-blind baseline, so no gain is "
                      "claimed for: " + "; ".join(
                          f"{r['metric']} ({r['adapted']:.2f} vs trivial {r['trivial_baseline']:.2f})" for r in not_learned
                      ) + ".", ""]
            if any(r["small_sample"] for r in rows):
                L += ["⚠ Rows marked *small n* have fewer than 100 examples (a ±15-point swing is noise there). "
                      "The debug run proves the pipeline, not the adaptation effect.", ""]
    L += [END]
    return "\n".join(L)


def exit_criteria(modes: list[str]) -> str:
    rows = []
    for mode in modes:
        d = EVIDENCE / mode
        manifest, summ = load(d / "final_manifest.json"), load(d / "train_summary.json")
        table = load(d / "before_after.json") or []
        events = load(d / "events.jsonl") or []
        cost = load(d / "cost.json") or {}
        rows += [
            (mode, "checkpoint at M2_CKPT_DIR/final, nonzero size",
             bool(manifest and manifest["files"].get("adapter_model.safetensors", {}).get("bytes", 0) > 0)),
            (mode, "loss history shows loss decreasing", bool(summ and summ["loss_decreased"] and not summ["loss_any_nan"])),
            (mode, "resume-after-interruption tested", any(e["event"] == "resumed" for e in events)),
            (mode, "before/after table with n (VQA + captioning/grounding)",
             {r["metric"].split(" —")[0] for r in table} >= {"VQA", "Grounding"} and all(r["n"] for r in table)),
            (mode, "actual GPU hours & cost recorded (complete billing)",
             cost.get("status") == "actual" and cost.get("gpu_hours_A10G", 0) > 0),
        ]
    lines = ["### Exit criteria (computed from the evidence files)", "", "| Run | Criterion | Met |", "|---|---|---|"]
    lines += [f"| {m} | {c} | {'✅' if ok else '❌'} |" for m, c, ok in rows]
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--mode", action="append", choices=["debug", "scaled"], required=True)
    ap.add_argument("--no-fetch", action="store_true", help="only regenerate STATUS.md from exported files")
    args = ap.parse_args()

    if not args.no_fetch:
        vol = modal.Volume.from_name(VOLUME_NAME)
        for f in ("conversion.json", "verification.json"):
            fetch(vol, f"{MODEL_DIR}/{f}", EVIDENCE / "geochat_conversion" / f)
        for mode in args.mode:
            info = export(mode, vol)
            print(mode, "fetched:", {k: v for k, v in info["fetched"].items() if v}, "cost:", info["cost"].get("status"))

    body = section(args.mode).replace(END, exit_criteria(args.mode) + "\n\n" + END)
    text = STATUS.read_text()
    if BEGIN in text and END in text:
        text = text[: text.index(BEGIN)] + body + text[text.index(END) + len(END):]
    else:
        text = text.rstrip() + "\n\n" + body + "\n"
    STATUS.write_text(text)
    print(f"updated {STATUS.relative_to(REPO)}")


if __name__ == "__main__":
    main()
